language: python
python:
  - "2.7"
install:
  - pip install -r api/requirements.txt
  - pip install -r api/dev-requirements.txt
script:
  - nosetests --with-coverage --cover-package=api
after_success:
  - coveralls